---

- hosts: LAB_ubuntu, LAB_centos, LAB_debian
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in "'Debian', 'Ubuntu'"  

  - name: Install Apache service
    apt:
      name: apache2
    when: ansible_distribution in "'Debian', 'Ubuntu'" 

  - name: Install PHP package for Apache
    apt:
      name: libapache2-mod-php 
    when: ansible_distribution in "'Debian', 'Ubuntu'" 
  


  - name: Update repository index on CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"  

  - name: Install HTTPD package on CentOS VMs
    dnf:
      name: httpd
    when: ansible_distribution == "CentOS" 

  - name: Install PHP support package for HTTPD on CentOS
    dnf:
      name: php 
    when: ansible_distribution == "CentOS" 

