---

- hosts: LAB
  become: true
  tasks:

  - name: Install updates (Ubuntu, Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in "'Debian', 'Ubuntu'"  

  - name: Install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"



- hosts: webservers
  become: true
  tasks: 

  - name: Install Apache and PHP support service
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package  }}"
      state: latest
 

- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package
    package:
      name: 
        - "{{ mariadb_package }}"
      state: latest



- hosts: file_servers
  become: true
  tasks:

  - name: Install files server
    package:
      name: 
        - samba
      state: latest

