---

- hosts: LAB
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in "'Debian', 'Ubuntu'"  

  - name: Uninstall Apache and PHP support service
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution in "'Debian', 'Ubuntu'" 
 


  - name: Update repository index on CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"  

  - name: Uninstall HTTPD package on CentOS VMs
    dnf:
      name: 
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS" 
