---

- hosts: all
  become: true
  tasks:

  - name: Install updates (Ubuntu, Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in "'Debian', 'Ubuntu'"  

  - name: Install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


- hosts: workstations
  tags: terraform_install
  become: true
  tasks:

    - name: Instal unzip
      package:
        name: unzip

    - name: Install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.2.6/terraform_1.2.6_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: webservers
  tags: apache,apache2,httpd
  become: true
  tasks: 

  - name: Install Apache and PHP support service
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package  }}"
      state: latest

  - name: Expose port 80 in firewalld (CentOS)
    tags: apache,apache2,httpd
    ansible.posix.firewalld:  
      port: 80/tcp
      permanent: true
      state: enabled
    when: ansible_distribution == "CentOS"
    register: firewalld

  - name: Restart firewalld after expose a port 80/tcp (CentOS)
    service: 
      name: firewalld
      state: restarted
    when: firewalld.changed

  - name: Start htttpd service (CentOS)
    tags: apache,apache2,httpd
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"

  - name: Copy default html file to site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  tags: maria,db,mariadb
  become: true
  tasks:

  - name: Install mariadb package
    package:
      name: 
        - "{{ mariadb_package }}"
      state: latest



- hosts: file_servers
  tags: samba
  become: true
  tasks:

  - name: Install files server
    package:
      name: 
        - samba
      state: latest

